name: Snapshot Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  snapshot:
    if: ${{ !contains(github.event.commits[0].message, 'nosnapshot') }}
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: check skip tag
        run: |
          if git log -1 --pretty=%B | grep -qE 'chore: release|nosnapshot'; then
            echo "Skipping snapshot release due to commit message."
            exit 0
          fi

      - uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ./.yarn/cache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      - uses: volta-cli/action@v4.1.1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: yarn
      - run: yarn lint:test
      - run: yarn test
      - run: yarn build:core
      - run: yarn build:web

      - name: Copy readme.md to packages
        run: |
          for dir in $(find packages -type d -maxdepth 1); do
            cp readme.md $dir/readme.md
          done
          
      - name: Snapshot Versioning
        run: yarn changeset version --snapshot

      - name: Snapshot Release
        run: |
          if git diff --quiet; then
            echo "No changes detected"
            exit 0
          else
            yarn changeset publish --no-git-tag --tag snapshot
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
